### ISSUE TITLE
Invalid route to publish assets?

### ISSUE THREAD

**Issue by thattejada** [mackrais/yii2-crop-image-section#1]
Hi @mackrais

I installed using:
```
php composer.phar require --prefer-dist mackrais/yii2-crop-image-section "dev-master"
```
And configured my form according to the example:
```php
use mackrais\cropimage\ImageCropSection;
```

But i'm getting this error:
![screen shot 2017-05-18 at 12 21 24 pm](https://cloud.githubusercontent.com/assets/3412546/26215179/f5e37edc-3bc4-11e7-8450-841f5159c356.png)

It's trying to create a folder from the root of the app to this route: [app_root]**/widgets/MrCropImageSection/assets**

Any advice or suggestion?

Thank you very much!

**Comment by mackrais** [comment]
Hi @diegotejadav !  Are you set in web.php component asset ?

        // Assets js and css
        'assetManager' => [
            'class' => 'yii\web\AssetManager',
            'linkAssets' => true,
            'forceCopy' => YII_ENV_DEV ? true : false,
        ],

You installed  this plugin "fxp/composer-asset-plugin:~1.1.1" ?

```
php composer.phar require --prefer-dist "fxp/composer-asset-plugin:~1.1.1" 
```

**Comment by douglas-srs** [comment]
I have the same error, I solved it by creating the folder structure @app/widgets/MrCropImageSection/assets and then pasting your css and js folders in there.
